name: rimai_app
description: Plataforma terapéutica adaptativa IA para niños con TEA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navegación y estado
  go_router: ^13.0.0
  flutter_riverpod: ^2.5.0
  
  # HTTP y red
  dio: ^5.4.0
  http: ^1.6.0
  
  # Base de datos local (offline)
  sqflite: ^2.3.0
  path: ^1.9.0
  uuid: ^4.5.3
  
  # Autenticación JWT
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # Notificaciones FCM
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  

  
  
  # UI y accesibilidad
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  
  # Reportes / exportación
  pdf: ^3.10.0
  share_plus: ^9.0.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  
  # Conectividad (offline detection)
  connectivity_plus: ^6.0.0
  fl_chart: ^1.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
